---
os_list:

  - name: "Rocky Linux 8"
    bootstrap_repo: "rockylinux-8-x86_64-uyuni"
    channels:
      - "rockylinux8-x86_64"
      - "rockylinux8-x86_64-appstream"
      - "rockylinux8-x86_64-extras"
      - "rockylinux8-uyuni-client-x86_64"

  - name: "Rocky Linux 9"
    bootstrap_repo: "rockylinux-9-x86_64-uyuni"
    channels:
      - "rockylinux9-x86_64"
      - "rockylinux9-x86_64-appstream"
      - "rockylinux9-x86_64-extras"
      - "rockylinux9-uyuni-client-x86_64"

  - name: "Ubuntu 24.04"
    bootstrap_repo: "ubuntu-24.04-amd64-uyuni"
    channels:
      - "ubuntu-24.04-pool-amd64-uyuni"
      - "ubuntu-2404-amd64-main-uyuni"
      - "ubuntu-2404-amd64-main-updates-uyuni"
      - "ubuntu-2404-amd64-main-security-uyuni"
      - "ubuntu-2404-amd64-uyuni-client"

  - name: "Debian 12"
    bootstrap_repo: "debian12-amd64-uyuni"
    channels:
      - "debian-12-pool-amd64-uyuni"
      - "debian-12-amd64-main-updates-uyuni"
      - "debian-12-amd64-main-security-uyuni"
      - "debian-12-amd64-uyuni-client"
